# ssh hub
# Create host/ssh key: ssh-keygen -t ed25519 -f ~/name.sk -C name
# chmod 600 name.sk
# ssh -i id_ed25519 -p 2222 root@127.0.0.1
# rsync -av --delete -e "ssh -p 2222 -i id_ed25519" root@127.0.0.1:/root/testdata ~/backup
# rsync -av --delete -e "ssh -p 2222 -i id_ed25519" ~/backup root@127.0.0.1:/root/testdata
# rsync -av --delete rsync://root@127.0.0.1:2222/vol ~/backup

volumes:
  test-data:

services:
  ssh:
    image: archidoc422/sshh
    ports:
      - "2222:2222"
    user: "2000:2000"
    environment:
      TZ: Asia/Tokyo
      SSH_PORT: 2222
      SSH_USER: ubuntu
      SSH_PUBLIC_KEY: ${SSH_PUBLIC_KEY}
      HOST_PRIVATE_KEY: |-
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
        QyNTUxOQAAACBIbQfPhEC0bN2WhqXF46xYHYB5Td4pWpbCWCfievqTIwAAAJCTKnm5kyp5
        uQAAAAtzc2gtZWQyNTUxOQAAACBIbQfPhEC0bN2WhqXF46xYHYB5Td4pWpbCWCfievqTIw
        AAAEDjk41YaFLaLCCPtSTeF/jMzmzNloGZ1pDvEjV0VYpmxkhtB8+EQLRs3ZaGpcXjrFgd
        gHlN3ilalsJYJ+J6+pMjAAAACmtheUBkZXNrLTUBAgM=
        -----END OPENSSH PRIVATE KEY-----
      ALLOW_USERS: "ubuntu" #"*@10.* *@172.* *@192.168.*" # /etc/ssh/sshd_config "root" "root@127.0.0.1"
      StartupCommand1: "touch /home/ubuntu/Hello2"
      StartupCommand2: "sudo chown ubuntu /home/ubuntu/testdata"
      CronJob1: "* * * * * touch /home/ubuntu/cronfile1"
    volumes:
      - test-data:/home/ubuntu/testdata
    restart: unless-stopped
    healthcheck:
      test: timeout 3s bash -c ':> /dev/tcp/127.0.0.1/2222' || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

